name: Test conditional fe workflow
on:
  push:
    paths:
      - 'packages/frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'packages/frontend/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Run frontend
        run: |
          echo "Testing frontend"
          pnpm frontend
